/**
 * API-nCoV2019
 * nCoV 2019 API provides information related with the case of pneumonia associated with the COVID-19 coronavirus.  The data we provide is collected from World Health Organization (WHO), the US Centers for Disease Control and Prevention (CDC), the Chinese Centre for Disease Control and Prevention (ECDC), China’s National Health Commission, and Chinese website DXY which provides regional case estimates faster than the national level reporting organizations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiNCoV2019) {
      root.ApiNCoV2019 = {};
    }
    root.ApiNCoV2019.ResultCasesCountry = factory(root.ApiNCoV2019.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ResultCasesCountry model module.
   * @module org.wso2.client.model.API-nCoV2019/ResultCasesCountry
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResultCasesCountry</code>.
   * @alias module:org.wso2.client.model.API-nCoV2019/ResultCasesCountry
   * @class
   * @param data {Number} 
   * @param _date {String} 
   */
  var exports = function(data, _date) {
    var _this = this;

    _this['data'] = data;
    _this['date'] = _date;
  };

  /**
   * Constructs a <code>ResultCasesCountry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.wso2.client.model.API-nCoV2019/ResultCasesCountry} obj Optional instance to populate.
   * @return {module:org.wso2.client.model.API-nCoV2019/ResultCasesCountry} The populated <code>ResultCasesCountry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'Number');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;



  return exports;
}));


